spring.application.name=CRUD
# Configuración de conexión a PostgreSQL
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/CRUDEmployee
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Inicialización SQL (opcional, para scripts)
spring.sql.init.platform=postgres

# Mostrar queries en consola
spring.jpa.show-sql=true
